# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# required
version: 2

# sphinx configuration
sphinx:
  configuration: PostProcessing/doc/src/conf.py

# don't build your docs in additional formats such as PDF and ePub
formats: []

# set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: PostProcessing/doc/src/requirements.txt
    - method: pip
      path: PostProcessing
